// api/kpi-digest.ts
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import { Resend } from "resend";

const TO_EMAIL = process.env.DIGEST_TO_EMAIL || 'vicvalch@hrkey.xyz';
const FROM_EMAIL = process.env.DIGEST_FROM_EMAIL || 'HRKey <no-reply@hrkey.xyz>';

/**
 * Lazy Supabase client initialization
 * Prevents build-time errors by initializing only when called
 */
function getSupabaseClient(): SupabaseClient {
  const supabaseUrl =
    process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey =
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    throw new Error(
      "Missing Supabase credentials. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY."
    );
  }

  return createClient(supabaseUrl, supabaseKey);
}

/**
 * Lazy Resend client initialization
 */
function getResendClient() {
  if (!process.env.RESEND_API_KEY) {
    return null;
  }
  return new Resend(process.env.RESEND_API_KEY);
}

function todayRangeLocalTZ(tz: string) {
  // Construye el rango [inicio,hoy_fin) en tz local (Costa Rica en tu caso)
  const now = new Date();
  const fmt = new Intl.DateTimeFormat('en-CA', { timeZone: tz, year:'numeric', month:'2-digit', day:'2-digit' });
  const parts = fmt.formatToParts(now).reduce((a, p) => (a[p.type]=p.value, a), {} as any);
  const y = parts.year, m = parts.month, d = parts.day;
  const start = new Date(`${y}-${m}-${d}T00:00:00-06:00`); // CR -06:00
  const end   = new Date(`${y}-${m}-${d}T23:59:59-06:00`);
  return { y, m, d, start, end };
}

function escapeHtml(s:string) {
  return String(s).replace(/[&<>"']/g, (m) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'} as any)[m]);
}

function buildHtml(items:any[]) {
  const rows = items.map((it, i) => `
    <tr>
      <td style="padding:8px; border:1px solid #ccc; text-align:center;">${i+1}</td>
      <td style="padding:8px; border:1px solid #ccc;">${escapeHtml(it.title || '')}</td>
      <td style="padding:8px; border:1px solid #ccc;">${escapeHtml(it.description || '')}</td>
      <td style="padding:8px; border:1px solid #ccc; font-size:11px; color:#666;">
        ${escapeHtml(it.position_hint || '')}<br/>
        ${escapeHtml(it.company_hint || '')}
      </td>
      <td style="padding:8px; border:1px solid #ccc; font-size:11px; color:#666;">
        ${escapeHtml(it.user_email || '')}
      </td>
      <td style="padding:8px; border:1px solid #ccc; font-size:11px; color:#999;">
        ${it.created_at ? new Date(it.created_at).toLocaleString('es-CR', {timeZone:'America/Costa_Rica'}) : ''}
      </td>
    </tr>
  `).join('\n');

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"/><title>HRKey Daily KPI Digest</title></head>
<body style="font-family:Arial,sans-serif; margin:0; padding:20px; background:#f9f9f9;">
  <div style="max-width:900px; margin:auto; background:white; padding:20px; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.1);">
    <h1 style="color:#333; margin-bottom:0;">HRKey Daily KPI Suggestions</h1>
    <p style="color:#666; margin-top:8px; margin-bottom:24px;">
      <strong>${items.length}</strong> suggestion(s) received today.
    </p>
    <table style="width:100%; border-collapse:collapse; font-size:13px;">
      <thead>
        <tr style="background:#f0f0f0;">
          <th style="padding:10px; border:1px solid #ccc; text-align:left;">#</th>
          <th style="padding:10px; border:1px solid #ccc; text-align:left;">Title</th>
          <th style="padding:10px; border:1px solid #ccc; text-align:left;">Description</th>
          <th style="padding:10px; border:1px solid #ccc; text-align:left;">Hints</th>
          <th style="padding:10px; border:1px solid #ccc; text-align:left;">User</th>
          <th style="padding:10px; border:1px solid #ccc; text-align:left;">Created</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
      </tbody>
    </table>
    <p style="margin-top:24px; font-size:12px; color:#999; border-top:1px solid #eee; padding-top:16px;">
      This is an automated daily digest generated by HRKey backend.
    </p>
  </div>
</body>
</html>
`;
}

export default async function handler(req:any, res:any) {
  if (req.method !== 'POST' && req.method !== 'GET') {
    return res.status(405).json({ ok:false, error:'Only POST/GET allowed' });
  }

  try {
    // Initialize clients inside handler (not at module scope)
    const supabase = getSupabaseClient();
    const resend = getResendClient();

    const tz = 'America/Costa_Rica';
    const { y, m, d, start, end } = todayRangeLocalTZ(tz);

    const { data, error } = await supabase
      .from('kpi_suggestions')
      .select('*')
      .gte('created_at', start.toISOString())
      .lte('created_at', end.toISOString())
      .order('created_at', { ascending: false });

    if (error) throw error;

    const items = data ?? [];
    console.log(`[kpi-digest] Found ${items.length} suggestions for ${y}-${m}-${d} (${tz})`);

    if (items.length === 0) {
      return res.status(200).json({ ok:true, count:0, message:'No suggestions today' });
    }

    const htmlBody = buildHtml(items);

    if (!resend) {
      console.warn('[kpi-digest] RESEND_API_KEY not set, skipping email send');
      return res.status(200).json({
        ok:true,
        count:items.length,
        message:'Email not sent (RESEND_API_KEY missing)',
        preview: htmlBody
      });
    }

    const emailRes = await resend.emails.send({
      from: FROM_EMAIL,
      to: TO_EMAIL,
      subject: `HRKey Daily KPI Suggestions - ${y}-${m}-${d} (${items.length} new)`,
      html: htmlBody,
    });

    console.log('[kpi-digest] Email sent:', emailRes);

    return res.status(200).json({ ok:true, count:items.length, emailId: (emailRes as any).id });
  } catch (e:any) {
    console.error('[kpi-digest] error:', e);
    return res.status(500).json({ ok:false, error: e.message });
  }
}
